apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
  namespace: <prenom>  
spec:
  selector:
    matchLabels:
      tiers: db
  template:
    metadata:
      labels:
        tiers: db
    spec:
      containers:
      - name: mongo-db
        image: mongo:5.0.3
        ports:
        - containerPort: 27017
        envFrom:
        - secretRef:
            name: ###